# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/vivado_prj/CPU_CDE/mycpu_verify/run_vivado/soc_lite.xdc

# IP: D:/vivado_prj/CPU_CDE/mycpu_verify/rtl/xilinx_ip/inst_ram/inst_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_ram || ORIG_REF_NAME==inst_ram} -quiet] -quiet

# IP: ip/signed_divider/signed_divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==signed_divider || ORIG_REF_NAME==signed_divider} -quiet] -quiet

# IP: ip/unsigned_divider/unsigned_divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unsigned_divider || ORIG_REF_NAME==unsigned_divider} -quiet] -quiet
