# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ceba_/Documents/working/verilog/CPU_CDE/mycpu_verify/run_vivado/soc_lite.xdc

# IP: ip/signed_divider/signed_divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==signed_divider || ORIG_REF_NAME==signed_divider} -quiet] -quiet

# IP: ip/unsigned_divider/unsigned_divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unsigned_divider || ORIG_REF_NAME==unsigned_divider} -quiet] -quiet
